server:
  port: 8080
  servlet:
    context-path: '/'

spring.datasource:
  url: 'jdbc:mysql://localhost:3306/kata'
  username: 'root'
  password: '12345'

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true